# Generated by Django 5.1.2 on 2025-01-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_image_listing_main_image_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
