# Generated by Django 5.1.2 on 2025-01-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='main_image',
            new_name='image',
        ),
    ]
